name: Deploy FTND Project to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ftnd-notebook-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ftnd-notebook-app
      # - name: Logout from Docker Hub
      #   run: docker logout
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify deployment success
      #   run: echo "Deployment to Docker Hub successful!"
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   if: success()
      # - name: Notify deployment failure
      #   run: echo "Deployment to Docker Hub failed!"
      #   if: failure()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Clean up Docker images
      #   run: docker rmi ${{ secrets.DOCKER_USERNAME }}/ftnd-notebook-app
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Final cleanup
      #   run: docker system prune -f
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      # - name: Notify cleanup success
      #   run: echo "Cleanup of Docker images successful!"
      #   if: success()
      # - name: Notify cleanup failure
      #   run: echo "Cleanup of Docker images failed!"
      #   if: failure()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Final notification
      #   run: echo "Deployment and cleanup process completed!"
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   if: always()
      # - name: Notify workflow completion
      #   run: echo "Workflow completed successfully!"
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify workflow failure
      #   run: echo "Workflow failed!"
      #   if: failure()     
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Final cleanup notification
      #   run: echo "Final cleanup completed!"
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify final cleanup success    
      #   run: echo "Final cleanup successful!"
      #   if: success()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify final cleanup failure
      #   run: echo "Final cleanup failed!"
      #   if: failure()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify deployment and cleanup completion
      #   run: echo "Deployment and cleanup process completed successfully!"
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify deployment and cleanup failure
      #   run: echo "Deployment and cleanup process failed!"
      #   if: failure()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Final notification      
      #   run: echo "Final notification sent!"
      #   if: always()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify final notification success
      #   run: echo "Final notification successful!"
      #   if: success()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify final notification failure
      #   run: echo "Final notification failed!"
      #   if: failure()       
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify workflow completion success    
          
      #   run: echo "Workflow completed successfully!"
      #   if: success()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Notify workflow completion failure
      #   run: echo "Workflow failed!"
      #   if: failure()
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}